theme: jekyll-theme-minimal
title: Jewish Resources
description: Resources for deassimilating Jews, those who wish to reconnect with Judaism and for those currently converting.
logo: https://imgur.com/EYDYYpT.jpg
show_downloads: false
